### ISSUE TITLE
KeyError: 'ema'

### ISSUE THREAD

**Issue by doInfinitely** [tqch/ddpm-torch#19]
When I used the following command with your provided checkpoint
python generate.py --dataset cifar10 --chkpt-path cifar10_2040.pt --use-ddim --skip-schedule quadratic --subseq-size 100 --suffix _ddim --num-gpus 2

I receive the following error:
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/remy/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 75, in _wrap
    fn(i, *args)
  File "/home/remy/ddpm-torch/generate.py", line 72, in generate
    state_dict = torch.load(chkpt_path, map_location=device)["ema"]["shadow"]
KeyError: 'ema'

**Comment by tqch** [comment]
Fixed 52a56bb2578cebaa9901287b2e6f74ead3b01773
